# Generated by Django 5.2.1 on 2025-06-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='scheduled_date',
            field=models.DateTimeField(default='2025-06-01 12:00:00'),
            preserve_default=False,
        ),
    ]
