# Generated by Django 5.2.3 on 2025-06-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0008_participantstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantstate",
            name="raised_hand",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="participantstate",
            name="screen_sharing",
            field=models.BooleanField(default=False),
        ),
    ]
